//app

export const SWITCH_LOADING_STATUS = 'SWITCH_LOADING_STATUS';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const CLEAR_ERROR_AND_LOADING = 'CLEAR_ERROR_AND_LOADING';


// tickers

export const SET_TICKERS_DATA = 'SET_TICKERS_DATA';